#!/usr/bin/env node
"use strict";
const { generatorHandler } = require("@prisma/generator-helper");
const fs = require("fs");
const path = require("path");

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./generated/nested-ops-meta",
      prettyName: "Prisma Nested Operations Metadata",
    };
  },
  async onGenerate(options) {
    const outputDir = options.generator.output?.value;
    if (!outputDir) return;

    const models = options.dmmf.datamodel.models;
    const relationMeta = {};

    for (const model of models) {
      relationMeta[model.name] = {};
      for (const field of model.fields) {
        if (field.kind === "object" && field.relationName) {
          relationMeta[model.name][field.name] = {
            kind: field.kind,
            isList: field.isList,
            type: field.type,
            relationName: field.relationName,
          };
        }
      }
    }

    const content =
      `// Auto-generated by prisma-extension-nested-operations — do not edit\n` +
      `export type RelationFieldMeta = { kind: string; isList: boolean; type: string; relationName: string };\n` +
      `export type RelationMeta = Record<string, Record<string, RelationFieldMeta>>;\n` +
      `export const relationMeta: RelationMeta = ` +
      `${JSON.stringify(relationMeta, null, 2)};\n`;

    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(path.join(outputDir, "index.ts"), content);
  },
});
