#!/usr/bin/env node
"use strict";
const { generatorHandler } = require("@prisma/generator-helper");
const fs = require("fs");
const path = require("path");

generatorHandler({
  onManifest() {
    return {
      defaultOutput: "./generated/nested-ops-meta",
      prettyName: "Prisma Nested Operations Metadata",
    };
  },
  async onGenerate(options) {
    const outputDir = options.generator.output?.value;
    if (!outputDir) return;

    const models = options.dmmf.datamodel.models;
    const modelsMeta = {};

    for (const model of models) {
      const uniqueFields = model.fields
        .filter((f) => f.isId || f.isUnique)
        .map((f) => f.name);

      const uniqueIndexFields = (model.uniqueFields || [])
        .map((fields) => fields.join("_"));

      const relations = model.fields
        .filter((f) => f.kind === "object" && f.relationName)
        .map((f) => ({
          name: f.name,
          kind: f.kind,
          isList: f.isList,
          type: f.type,
          relationName: f.relationName,
        }));

      modelsMeta[model.name] = { uniqueFields, uniqueIndexFields, relations };
    }

    const content =
      `// Auto-generated by prisma-extension-nested-operations — do not edit\n` +
      `export type RelationField = { name: string; kind: string; isList: boolean; type: string; relationName: string };\n` +
      `export type ModelsMeta = Record<string, { uniqueFields: string[]; uniqueIndexFields: string[]; relations: RelationField[] }>;\n` +
      `export const modelsMeta: ModelsMeta = ` +
      `${JSON.stringify(modelsMeta, null, 2)};\n`;

    fs.mkdirSync(outputDir, { recursive: true });
    fs.writeFileSync(path.join(outputDir, "index.ts"), content);
  },
});
